### ISSUE TITLE
Bloccknig stuck at 0%

### ISSUE THREAD

**Issue by SjurWarEagle** [dmstern/likers-blocker#189]
Hi,

I'm trying to block the likes of this:
https://twitter.com/ifeelgoodanja/status/1684624558542757889/likes

but it stays at 0%, even after 5min. Console reports some erros:
<img width="571" alt="image" src="https://github.com/dmstern/likers-blocker/assets/7311103/b6dcb881-d5e7-4e02-9373-fba1e8d86822">
this repeats over and over again, I would say once per second.

**Comment by ArtemyKozodaev** [comment]
Same problem, in Edge and Chrome

**Comment by brinkie** [comment]
Same problem here. Progress stuck at 0% and repeatedly the same errors in the console

index.js:1     GET https://api.twitter.com/1.1/statuses/show.json?id=1691495012125618178 404
(anonymous) @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
sendGetRequest @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
getTweet @ index.js:1
(anonymous) @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
getTotalUsersCount @ index.js:1
(anonymous) @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
collectUsers @ index.js:1
(anonymous) @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
scrollDown @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
(anonymous) @ index.js:1
setInterval (async)
(anonymous) @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
startScrolling @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
initBlockAction @ index.js:1
(anonymous) @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
setUpBlockPopup @ index.js:1
(anonymous) @ index.js:1
Show 77 more frames
Show less
index.js:1 No tweet found Response {type: 'cors', url: 'https://api.twitter.com/1.1/statuses/show.json?id=1691495012125618178', redirected: false, status: 404, ok: false, …}
(anonymous) @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
getTweet @ index.js:1
(anonymous) @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
getTotalUsersCount @ index.js:1
(anonymous) @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
collectUsers @ index.js:1
(anonymous) @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
scrollDown @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
(anonymous) @ index.js:1
setInterval (async)
(anonymous) @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
startScrolling @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
initBlockAction @ index.js:1
(anonymous) @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
r @ index.js:1
Promise.then (async)
c @ index.js:1
(anonymous) @ index.js:1
e @ index.js:1
setUpBlockPopup @ index.js:1
(anonymous) @ index.js:1
Show 73 more frames
Show less
index.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'favorite_count')
    at st.<anonymous> (index.js:1:35490)
    at Generator.next (<anonymous>)
    at r (index.js:1:111)
